# Lesson 2 Assignment
### Jessica Kunkel

#### Question 1
1. Use the randn function to create an array with a dimension of 5X5 and use a for loop to calculate the sum of all elements in the diagonal of the array.

In [1]:
#!/usr/bin/env python
""" Import display functions and create a function to print outputs to 
Markdown """

from IPython.display import display, Markdown
def printmd(string):
    display(Markdown(string))

In [2]:
""" Use NumPy to generate a random 5x5 array. The array is printed.
The elements along the diagonal of the array are summed and printed 
as Markdown. """

import numpy as np

arr_x = np.random.randn(5, 5)

sum_arr = 0

for i in range(5):
    sum_arr += arr_x[i, i]

printmd("Random 5x5 array:")
print(f"{arr_x}\n")
printmd(f"Sum of all elements in the diagonal of the arrray = {sum_arr}")

Random 5x5 array:

[[-0.75447948  0.25759998  0.04023064 -0.57041052 -0.89836398]
 [-0.6892339   0.75433676 -0.09081475  0.60598496  1.94849998]
 [-0.55336956  0.10107639  1.38616314 -0.13999501 -0.89031138]
 [-0.17004846 -1.37876537  1.09236203 -0.95793502  0.10318649]
 [ 0.1707494  -0.07446528  0.98121798 -1.2133028   1.47451366]]



Sum of all elements in the diagonal of the arrray = 1.902599056651288

2. Choose any three functions to apply to this array.

In [3]:
""" The array is manipulated to calculate the mean of all elements in the 
array (function 1), the sum of the elements in each row (function 2), and 
to take the absolute value of negative elements in the array and return 
the array as a whole (function 3). """

printmd(f"Mean of the array: {arr_x.mean()}")
printmd(f"Sum across the rows: {arr_x.sum(0)}")
printmd(f"Changing negative elements in the array to their absolute values: \n")
print(f"{np.where(arr_x < 0, abs(arr_x), arr_x)}")

Mean of the array: 0.02137703558139905

Sum across the rows: [-1.996382   -0.34021752  3.40915904 -2.2756584   1.73752477]

Changing negative elements in the array to their absolute values: 


[[0.75447948 0.25759998 0.04023064 0.57041052 0.89836398]
 [0.6892339  0.75433676 0.09081475 0.60598496 1.94849998]
 [0.55336956 0.10107639 1.38616314 0.13999501 0.89031138]
 [0.17004846 1.37876537 1.09236203 0.95793502 0.10318649]
 [0.1707494  0.07446528 0.98121798 1.2133028  1.47451366]]


#### Question 2
1. Use x = np.random.randint(0, 1000, size = (10, 10)) to generate 10x10 array and use a for loop to find out how many even numbers are in it.

In [4]:
""" Use NumPy to generate a 10x10 array of random integers between 
0 and 1000 (np.random.randint). Then, use a for-loop to inspect each 
element. If the element is even, the count of even numbers (count_even) 
in the array is incremented by 1. The array is printed and the count of
even numbers is printed as Markdown. """

x = np.random.randint(0, 1000, size = (10, 10))
count_even = 0

for row in x:
    for element in row:
        if element % 2 == 0:
            count_even += 1

printmd("Random 10x10 array:")
print(f"{x}\n")
printmd(f"The number of even elements in the array \"x\" is {count_even}")

Random 10x10 array:

[[783 661 292 754 836 163  38 111 212 516]
 [545 875 982 536 581 680  43 213 508 649]
 [878 805 168 933 736 734 799 242 793 724]
 [994  95 935 428 538 688 705  72 512 797]
 [274  74 418 281 983 582 553 802 986 895]
 [820 413  28  26 220  78 728  94 543 829]
 [272  38 179 913 693 365 703 661  85 983]
 [375 335  20 392  71 187 707 266 434 314]
 [514 936  33 384 462 347 808 777 445 506]
 [294 255 609 958 573 783 303 611 330 277]]



The number of even elements in the array "x" is 51

2. Randomly generate an 8x9 array from a normal distribution with mean = 1, sigma = 0.5. Calculate the mean of elements whose indexes have a relation of (i+j)%5 == 0  (i is row index and j is column index).

In [5]:
""" Use NumPy to generate an 8x9 array from a normal distribution 
(np.random.normal) with mean = 1 (loc=1.0), sigma = 0.5 (scale=0.5).
The array is printed. Then, each element in the array is inspected 
using the relation (i + j) % 5 == 0, and elements meeting the condition
are added to the list rel_elements. The list is converted into an 
ndarray np_rel, and the mean of the elements whose indexes met the 
condition is calculated using np_rel.mean(). The elements are printed,
and the mean of the elements is displayed in Markdown. """

norm = np.random.normal(loc=1.0, scale=0.5, size=(8, 9))

printmd("8x9 array from normal distribution:")
print(f"{norm}\n")

rel_elements = []

for i in range(8):
    for j in range(9):
        if (i + j) % 5 == 0:
            rel_elements.append(norm[i,j])

np_rel = np.array(rel_elements)
mean_rel = np_rel.mean()

printmd(f"The elements whose indexes have a relation of (i+j)%5 == 0:")
print(f"{np_rel}\n")
printmd(f"The mean of the elements whose indexes have a relation of (i+j)%5 == 0 is {mean_rel}")

8x9 array from normal distribution:

[[ 1.57055881  1.14792983  1.07238742  1.41176743  1.33189694  0.76286913
   1.09741169  1.53513035  1.21851142]
 [ 0.82945534  1.10191324  0.70960084  1.40702107  0.1074345   1.38174061
   0.83428994  1.05637373  1.32486988]
 [ 1.26953157  0.62471211  1.09543509  0.65149983  0.71205682  1.49184087
   0.28536879  0.33116727  0.96860542]
 [ 0.44494116  0.58366253  1.46378798  0.63857387  0.89935129  1.36700164
   1.0856411   0.54384164  0.66439305]
 [ 0.34769686  0.09009092  1.10006992  0.65292724  1.50842879  1.17717486
   0.88792253  1.68700796  1.20301162]
 [ 1.70428913  1.06126382  1.20669711  0.73261151  1.00893094  0.76507394
   0.72692552  0.91523307  0.57068923]
 [ 1.04427897  1.08866893  0.96697509  1.1148737   0.69840018 -0.02399264
   0.35284463  0.92275081  0.95111252]
 [-0.04050376 -0.05048443  1.98163188  1.34357508  0.6653134   0.71779865
   1.46017054  0.37992449  1.234905  ]]



The elements whose indexes have a relation of (i+j)%5 == 0:

[1.57055881 0.76286913 0.1074345  0.65149983 0.96860542 1.46378798
 0.54384164 0.09009092 0.88792253 1.70428913 0.76507394 0.69840018
 1.34357508 1.234905  ]



The mean of the elements whose indexes have a relation of (i+j)%5 == 0 is 0.9137752923004235